### ISSUE TITLE
作者你好， 代码高亮不能正常工作, 麻烦看下

### ISSUE THREAD

**Issue by F1renze** [AlynxZhou/hexo-theme-aria#13]
已经按照说明文档的配置了， 代码高亮还是有问题, 尝试将内置的 `solarized-dark` 更换为下载的 `agate` css文件依然无效， 不太明白啥情况
[博客地址](http://www.f1renze.top)
`xx.github.io/_config.yml`:
```
highlight:
  enable: true
  hljs: true
  line_number: true
  auto_detect: false
  tab_replace:
```

`xx.github.io/themes/aria/_config.yml`:
```
# Available: atom-one-dark | atom-one-light | solarized-dark | solarized-light
highlight: agate
#solarized-dark
```
