### ISSUE TITLE
favicon的路径好像不对吧？

### ISSUE THREAD

**Issue by machao1990** [AlynxZhou/hexo-theme-aria#5]
```
favicon:
  apple_touch_icon: favicons/apple-touch-icon.png
  android_chrome_large: favicons/android-chrome-192x192.png
  medium: favicons/favicon-32x32.png
  small: favicons/favicon-16x16.png
  safari_pinned_tab: favicons/safari-pinned-tab.svg
  android_manifest: favicons/site.webmanifest
  ms_browserconfig: favicons/browserconfig.xml
  fallback: favicon.ico
```
fallback的路径应该也是favicons/favicon.ico吧，不然加载不到
